---
values:
  'Mail van Taalunie: Lisanne Teunissen (NTU), http://taalunie.org/':
  - WR-P-E-E-0000000018
  - WR-P-E-E-0000000019
  - WR-P-E-E-0000000020
  'Mail van Dedicon: Sjoerd Bunnik (FNB, tegenwoordig Dedicon), http://www.dedicon.nl/':
  - WR-P-P-D-0000000001
  - WR-P-P-D-0000000002
  - WR-P-P-D-0000000003
  - WR-P-P-D-0000000004
  - WR-P-P-D-0000000005
  - WR-P-P-D-0000000006
