---
values:
  taal- en spraaktechnologienieuws jul'03:
  - WR-P-E-E-0000000018
  taal- en spraaktechnologienieuws jun'03:
  - WR-P-E-E-0000000019
  taal- en spraaktechnologienieuws mei'03:
  - WR-P-E-E-0000000020
  fnb-bulletin:
  - WR-P-P-D-0000000001
  - WR-P-P-D-0000000002
  - WR-P-P-D-0000000004
