---
values:
  'Mail van Taalunie: Lisanne Teunissen (NTU), http://taalunie.org/':
  - 0
  - 1
  - 2
  'Mail van Dedicon: Sjoerd Bunnik (FNB, tegenwoordig Dedicon), http://www.dedicon.nl/':
  - 5
  - 4
  - 7
  - 6
  - 8
  - 3
